---
# MySQL Version: 5.7
# 
# FileVersion: 20191114

# Dockerfile
# https://github.com/docker-library/mysql/blob/master/5.7/Dockerfile
# https://github.com/docker-library/mysql/blob/master/5.7/docker-entrypoint.sh


# ####################################
# 环境变量
# ####################################


# ####################################
# 文件映射
# ####################################


version: '3'

services:

  mysql-g1-s1:
    image: ${MYSQL_IMG_TAG}
    restart: always
    hostname: mysql-g1-s1
    container_name: mysql-g1-s1
    volumes:
      - /etc/localtime:/etc/localtime
      - ./conf/gtid/yh-master.cnf:/etc/mysql/conf.d/yh-master.cnf
      - ./conf/nodes/g1-s1.cnf:/etc/mysql/conf.d/yh-node-id.cnf
      - ${XDC_MYSQL_GTID_DATA:-./data}/mysql-g1-s1:/var/lib/mysql
      - ${XDC_MYSQL_GTID_LOG:-./log}:/var/log/mysql
    ports:
      - ${MYSQL_G1_S1_PORT:-3316}:3306
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_MASTER_PASSWD}"
    networks:
      - mysql-cluster-g1

  mysql-g1-s2:
    image: ${MYSQL_IMG_TAG}
    restart: always
    hostname: mysql-g1-s2
    container_name: mysql-g1-s2
    depends_on:
      - mysql-g1-s1
    volumes:
      - /etc/localtime:/etc/localtime
      - ./conf/gtid/yh-slave.cnf:/etc/mysql/conf.d/yh-slave.cnf
      - ./conf/nodes/g1-s2.cnf:/etc/mysql/conf.d/yh-node-id.cnf
      - ${XDC_MYSQL_GTID_DATA:-./data}/mysql-g1-s2:/var/lib/mysql
      - ${XDC_MYSQL_GTID_LOG:-./log}:/var/log/mysql
    ports:
      - ${MYSQL_G1_S2_PORT:-3317}:3306
    environment:                           
      - "MYSQL_ROOT_PASSWORD=${MYSQL_SLAVE_PASSWD}"
    networks:
      - mysql-cluster-g1

  mysql-g1-s3:
    image: ${MYSQL_IMG_TAG}
    restart: always
    hostname: mysql-g1-s3
    container_name: mysql-g1-s3
    depends_on:
      - mysql-g1-s1
    volumes:
      - /etc/localtime:/etc/localtime
      - ./conf/gtid/yh-slave.cnf:/etc/mysql/conf.d/yh-slave.cnf
      - ./conf/nodes/g1-s3.cnf:/etc/mysql/conf.d/yh-node-id.cnf
      - ${XDC_MYSQL_GTID_DATA:-./data}/mysql-g1-s3:/var/lib/mysql
      - ${XDC_MYSQL_GTID_LOG:-./log}:/var/log/mysql
    ports:
      - ${MYSQL_G1_S3_PORT:-3318}:3306
    environment:                           
      - "MYSQL_ROOT_PASSWORD=${MYSQL_SLAVE_PASSWD}"
    networks:
      - mysql-cluster-g1


networks:
  mysql-cluster-g1:
    driver: bridge
