version: '3'
services:
    nexus:
        restart: always
        image: ${NEXUS_IMG_TAG}
        hostname: nexus
        container_name: nexus
        environment:
            - TZ=Asia/Shanghai
            - JAVA_MAX_HEAP=1200m
            - JAVA_MIN_HEAP=1200m
        volumes:
            - ./data/:/nexus-data/:z
        # ports:
        #     - ${NEXUS_PORT:-8081}:8081

    nginx:
        image: nginx:latest
        ports:
            - ${NEXUS_PORT:-8081}:80
        volumes:
            - ./conf/nginx/:/etc/nginx/conf.d/
        command: /bin/bash -c "nginx -g 'daemon off;'"
        links:
            - nexus
        ulimits:
            nproc: 655350
