---
# ZooKeeper Version: 3.4, 3.4.11
# https://hub.qiniu.com/store/library/zookeeper#page=tag
# FileVersion: 20191104

# Dockerfile
# https://github.com/31z4/zookeeper-docker/blob/af9250c7208973b74ed0ef6ca61052bdf853ce20/3.4.11/Dockerfile


# ####################################
# 环境变量
# ####################################


# ####################################
# 文件映射
# ####################################


version: '3'

services:
  sz-zk1:
    image: zookeeper:3.4
    restart: always
    hostname: sz-zk1
    container_name: sz-zk1
    ports:
      - ${ZK1_PORT:-2181}:2181
    volumes:
      - ${XDC_ZK_DATA:-./data}/sz-zk1:/data
      - ${XDC_ZK_LOG:-./log}/sz-zk1:/datalog
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=sz-zk1:2888:3888 server.2=sz-zk2:2888:3888 server.3=sz-zk3:2888:3888

  sz-zk2:
    image: zookeeper:3.4
    restart: always
    hostname: sz-zk2
    container_name: sz-zk2
    ports:
      - ${ZK2_PORT:-2182}:2181
    volumes:
      - ${XDC_ZK_DATA:-./data}/sz-zk2:/data
      - ${XDC_ZK_LOG:-./log}/sz-zk2:/datalog
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=sz-zk1:2888:3888 server.2=sz-zk2:2888:3888 server.3=sz-zk3:2888:3888

  sz-zk3:
    image: zookeeper:3.4
    restart: always
    hostname: sz-zk3
    container_name: sz-zk3
    ports:
      - ${ZK3_PORT:-2183}:2181
    volumes:
      - ${XDC_ZK_DATA:-./data}/sz-zk3:/data
      - ${XDC_ZK_LOG:-./log}/sz-zk3:/datalog
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=sz-zk1:2888:3888 server.2=sz-zk2:2888:3888 server.3=sz-zk3:2888:3888
